- name: conditions
  hosts: local
  connection: local
  vars: 
    number: 100
  tasks:
  - name: check the number is less than 5 or not
    ansible.builtin.debug:
      msg: "Given Number {{ number }} is less than 10 "
    when: number < 10
