- name: functions
  hosts: local
  connection: local
  vars: 
    techonologies: Devops, Linux, Shell, Ansible #String
    # dictionary == map
    tags:
      Application: payment
      Environment: dev
    # List
    listTags:
    - key: Application
      value: payment
    - key: Environment
      value: dev
  tasks:
  - name: default varaibles
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Radhika')}}"
  # String to list
  - name: converting string into list
    ansible.builtin.debug:
     msg: "Techonologies are: {{techonologies | split(',')}}"

  # map to list
  - name: converting Map into list
    ansible.builtin.debug:
     msg: "Tags are: {{ tags | dict2items }}"

  # list to map
  - name: convert list into map
    ansible.builtin.debug:
      msg: "tag map: {{ listTags | items2dict }}"

  - name: read yaml and take it into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml' | from_yaml)}}"
  
  - name: convert json into yaml
    ansible.builtin.debug:
    msg: "json: {{ student_yaml | to_json}}"

