- name: functions
  hosts: local
  connection: local
  vars: 
    techonologies: Devops, Linux, Shell, Ansible #String
    # dictionary == map
    tags:
      Application: payment
      Environment: dev
  tasks:
  - name: default varaibles
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Radhika')}}"
  # String to list
  - name: converting string into list
    ansible.builtin.debug:
     msg: "Techonologies are: {{techonologies | split(',')}}"

  # map to list
  - name: converting Map into list
    ansible.builtin.debug:
     msg: "Tags are: {{ tags | dict2items }}"
