- name: play level varaibles
  hosts: local
  connection: local
  vars:
    COURSE: Devops with AWS 
    DURATION: 10hrs
    Trainer: Radhika
  tasks:
  - name: Print the info
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer}}"
