- name: play level varaibles
  hosts: local
  connection: local
  vars:
    COURSE: Ansible 
    DURATION: 10hrs
    Trainer: Radhika
  tasks:
  - name: Print the info
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer}}"
