- name: variables as prompt
  hosts: local
  connection: local
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "Hello, Username is: {{username}} and password is: {{password}} "